### PR TITLE
ADD: Html escape parser

### PR DESCRIPTION
**Pull request by yopyzzang**

### CODE REVIEW

**Comment by daniel-sc** [comment]
Hi @yopyzzang 
thanks for creating a PR here!
I'd like to understand what the thing is you'd like to archive? 
Guessing: prevent escaping of xml special characters, such as `&` with `&amp;` etc.?)
If that is the case, maybe it'd make sense to add an corresponding option `--no-replace-xml-special-chars` to the upstream [daniel-sc/xliff-simple-merge](https://github.com/daniel-sc/xliff-simple-merge) - analogous to https://github.com/daniel-sc/xliff-simple-merge/issues/4 ?

**Comment by yopyzzang** [comment]
@daniel-sc Your guess is correct. 
Can I update that branch through my code?

**Comment by daniel-sc** [comment]
HI @yopyzzang I think it'd be the cleanest solution if you could create a new PR in daniel-sc/xliff-simple-merge that adds a new option `--no-replace-xml-special-chars` (analogous to https://github.com/daniel-sc/xliff-simple-merge/commit/839d6608f93786ecf8b044be2028400c1c96bb7d ) and after that is merged, you/we can create a new PR in this repo that exposes this option as well - does that make sense?

**Comment by daniel-sc** [comment]
Hi @yopyzzang 
I did some tests and it seems to me that with angular 13 as well the "native" `ng i18n-extract` does replace `& ` with `&amp;` etc. (which makes sense, since at least `<` and `>` would cause trouble otherwise). Could you indicate why you'd like a different behaviour?

**Comment by daniel-sc** [comment]
This is probably not meaningful as it would diverge from standard Angular v13+ behavior - see discussion in #7

**Comment by yopyzzang** [comment]
Hi @daniel-sc 
There seems to have been a significant communication issue in our previous discussion.
What I wanted to explain was that I am trying to resolve inconsistencies caused by escaped and unescaped special characters between the source translation file and the target translation file.

In our project, we upload translation files to an external translation platform, and translators often remove escape sequences and insert raw special characters during translation. As a result, merging updated files frequently leads to errors.

To address this issue, I submitted the PR so that special characters in the target files are properly parsed and escaped during the merge process. I would appreciate it if you could review it again with this context in mind.

Additionally, the following test case illustrates the issue clearly:
```
test('extract-and-merge xlf 2.0', async () => {
        await fs.writeFile('builder-test/messages.xlf', '<xliff version="2.0" xmlns="urn:oasis:names:tc:xliff:document:2.0" srcLang="de">\n' +
            '  <file original="ng.template" id="ngi18n">\n' +
            '    <unit id="ID1">\n' +
            '      <segment>\n' +
            '        <source>source & val</source>\n' +
            '      </segment>\n' +
            '    </unit>\n' +
            '    <unit id="ID2">\n' +
            '      <segment>\n' +
            '        <source>source & val2</source>\n' +
            '      </segment>\n' +
            '    </unit>\n' +
            '    <unit id="removeMeID3">\n' +
            '      <segment>\n' +
            '        <source>source val2</source>\n' +
            '      </segment>\n' +
            '    </unit>\n' +
            '  </file>\n' +
            '</xliff>', 'utf8');
        await fs.writeFile('builder-test/messages.fr.xlf', '<xliff version="2.0" xmlns="urn:oasis:names:tc:xliff:document:2.0" srcLang="de">\n' +
            '  <file original="ng.template" id="ngi18n">\n' +
            '    <unit id="ID1">\n' +
            '      <segment>\n' +
            '        <source>source & val</source>\n' +
            '        <target>target & val</target>\n' +
            '      </segment>\n' +
            '    </unit>\n' +
            '  </file>\n' +
            '</xliff>', 'utf8');

        // A "run" can have multiple outputs, and contains progress information.
        const run = await architect.scheduleTarget({project: 'builder-test', target: 'extract-i18n-merge'}, {
            format: 'xlf2',
            targetFiles: ['messages.fr.xlf'],
            outputPath: 'builder-test',
            removeIdsWithPrefix: ['removeMe']
        });

        // The "result" member (of type BuilderOutput) is the next output.
        await run.result;
        const result = await run.result;
        expect(result.success).toBeTruthy();

        // Stop the builder from running. This stops Architect from keeping
        // the builder-associated states in memory, since builders keep waiting
        // to be scheduled.
        await run.stop();

        // Expect that the copied file is the same as its source.
        const targetContent = await fs.readFile('builder-test/messages.fr.xlf', 'utf8');
        expect(targetContent).toEqual('<xliff version="2.0" xmlns="urn:oasis:names:tc:xliff:document:2.0" srcLang="de">\n' +
            '  <file original="ng.template" id="ngi18n">\n' +
            '    <unit id="ID1">\n' +
            '      <segment>\n' +
            '        <source>source &amp; val</source>\n' +
            '        <target>target &amp; val</target>\n' +
            '      </segment>\n' +
            '    </unit>\n' +
            '    <unit id="ID2">\n' +
            '      <segment state="initial">\n' +
            '        <source>source &amp; val2</source>\n' +
            '        <target>source &amp; val2</target>\n' +
            '      </segment>\n' +
            '    </unit>\n' +
            '  </file>\n' +
            '</xliff>');
    });
```

**Pull request closed without merging**
