### PR TITLE
Support for angular v19 #118

### LINKED ISSUE #118: Support Angular 19

### PR DESCRIPTION
**Pull request by martinboue**
Fixes #118 

All tests pass + manually tested with an Angular v19 app

### CODE REVIEW

**Comment by daniel-sc** [comment]
Could you update the CI config (.github/workflows/) to run all tests as well with angular 19?

(I know the pipeline is currently broken, I'll look into that tomorrow..)

**Comment by martinboue** [comment]
> Could you update the CI config (.github/workflows/) to run all tests as well with angular 19?
> 
> (I know the pipeline is currently broken, I'll look into that tomorrow..)

Thanks for your reactivity, done.

**Comment by martinboue** [comment]
@daniel-sc do you have any idea why the pipeline is broken? I'm guessing it uses a wrong node or typescript version for "Node.js CI / build (16.x, 13.2.6)". How can I help you with that?

**Comment by daniel-sc** [comment]
@martinboue I'm currenty trying to fix it in https://github.com/daniel-sc/ng-extract-i18n-merge/pull/120 - got it running locally, so I'm hopefull to get it repaired in the next hour - otherwise any help is higly appreciated :)

**Comment by daniel-sc** [comment]
@martinboue ok - I think I'm done for today - if you like, please take a look!

**Pull request merged**
